//

const Clarifai = require('clarifai');
const base64Img = require('base64-img');

const app = new Clarifai.App({
  apiKey : 'f0e78cd592a147b58a14e68d156ac5fc'
})


var data = base64Img.base64Sync('cat.jpeg');   // Example image
// Synchronous function, so no callback. There's an async one if you want to have better manners with your server time.

data = data.replace('data:image/jpeg;base64,', '');  // Replace prefix generated by base64Sync

app.models.predict(Clarifai.GENERAL_MODEL, {base64:data}).then(

  function(response) {
    console.log(JSON.stringify(response));   // TODO something else with the data - like return it via a callback
  },
  function(err) {
    console.error(err);  // TODO something more useful
  }
);
